version: '3'

tasks:
  build_image:
    desc: Build the Docker image 
    cmds:
      - task: 
      - task:
    status:

  build_dockerfile_image:
    desc: Builder the Docker image based on the current Dockerfile
    cmds:
    status:

  clone_julia:
    desc: Clone the Julia git repo
    cmds:
    status:

  build_julia:
    desc: Build Julia via Makefile
    cmds:
    status:
