version: '3'

env:
  BUILD_ENGINE:
    sh: which docker || printf /usr/bin/podman

tasks:
  default:
    cmds:
      - echo "juliaup_install (ju), julia_clone (jc), image_build (ib), prune (p), julia_build (jb)"
    silent: true

  juliaup_install:
    aliases: [ju]
    cmds:
      - curl -fsSL https://install.julialang.org | sh -s -- -y --default-channel nightly

  julia_clone:
    aliases: [jc]
    desc: Clone the Julia git repo
    cmds:
      - git clone https://github.com/JuliaLang/julia.git --single-branch

  image_build:
    aliases: [ib]
    desc: Builder the Docker image based on the current Dockerfile
    cmds:
      - ' {{.BUILD_ENGINE}} build -t test . '

  prune:
    aliases: [p]
    desc: Prune Docker-related data
    cmds: 
      - 'yes | {{.BUILD_ENGINE}} system prune -a' 

  julia_build:
    aliases: [jb]
    desc: Build Julia from git repo (set MARCH by passing a CLI argument)
    cmds:
      - cd julia && make -j4 MARCH={{.CLI_ARGS}}
    preconditions:
      - test -d julia
